- name: "Add jetstack Helm repository"
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: "Copy cert-manager Helm values"
  ansible.builtin.template:
    src: values.yaml
    dest: /tmp/cert-manager.values.yaml
    force: true
    mode: u=rw,g=r,o=r

- name: "Install cert-manager Helm chart"
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager_chart_version }}"
    namespace: cert-manager
    create_namespace: true
    values_files:
      - /tmp/cert-manager.values.yaml

- name: "Wait cert-manager deployment"
  kubernetes.core.k8s_info:
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
    wait: true

- name: "Copy letsencrypt production cluster issuer"
  ansible.builtin.template:
    src: letsencrypt-production.cluster-issuer.yaml
    dest: /tmp/letsencrypt-production.cluster-issuer.yaml
    force: true
    mode: u=rw,g=r,o=r

- name: "Install letsencrypt production cluster issuer"
  kubernetes.core.k8s:
    src: /tmp/letsencrypt-production.cluster-issuer.yaml
    state: present
