{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace  | quote }}
  name: {{ template "wordpress.fullname" . }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  WORDPRESS_DB_USER: {{ .Values.secret.databaseUsername | b64enc | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.secret.databasePassword | b64enc | quote }}
{{- end }}