apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wordpress
  name: wordpress
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/instance: "wordpress-001"
    app.kubernetes.io/version: "6.4.3"
    app.kubernetes.io/managed-by: "helm"
data:
  WORDPRESS_DB_HOST: "FILL_ME"
  WORDPRESS_DB_NAME: "FILL_ME"