apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: wordpress
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/instance: "wordpress-001"
    app.kubernetes.io/version: "6.4.3"
    app.kubernetes.io/managed-by: "helm"
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"