apiVersion: v1
kind: Secret
metadata:
  namespace: wordpress
  name: wordpress
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/instance: "wordpress-001"
    app.kubernetes.io/version: "6.4.3"
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  WORDPRESS_DB_USER: "FILL_ME"
  WORDPRESS_DB_PASSWORD: "FILL_ME"